#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Usage: test <mongo_release> [data_dir]"
    echo "e.g. test mongodb-linux-x86_64-ubuntu1204-3.4.2 travis/mongodb/data"
fi

release=$1
data_dir=${2:-travis/mongodb/data}

data="$data_dir/$release"
data_ssl="$data-ssl"
mkdir -p $data $data_ssl

$install_dir/$release/bin/mongod --fork --dbpath $data --syslog --port 27017
$install_dir/$release/bin/mongod --fork --dbpath $data_ssl --syslog --port 27018 --sslMode requireSSL --sslPEMKeyFile tests/ssl/server.pem --sslCAFile tests/ssl/ca.pem

cargo test --features ssl --verbose
